package fact.exceptions;

public class TestA {

	void fn()  {
		throw new TestRuntimeException("Testing");
	}
}
